name: Update sources

on:
 # schedule:
#    - cron:  '25,55 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.x'
    - name: Install packages
      run: |
        pip install altparse
    - name: Run python scripts
      run: |
        export GITHUB_TOKEN="${{ secrets.ACCESS_TOKEN }}"
        python update.py
    - name: Git add and commit
      uses: EndBug/add-and-commit@v9.1.3
      with:
        add: '--all'
        default_author: github_actions
